spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUPID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  eureka:
    client:
      service-url:
        defaultZone: ${DEFAULTZONE}

  grpc:
    client:
      user-service:
        address: ${USER_SERVICE_GRPC_ADDRESS}

server:
  port: ${SERVER_PORT}

