spring.application.name=catalog_service
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=catalog_db



error.util.ErrorKeys.category.alreadyExist = Category with name [{0}] already exists;
error.util.ErrorKeys.category.notFound = Category not found with id: [{0}];
error.util.ErrorKeys.category.successfullyCreated = The category with id=[{0}] was successfully created;
error.util.ErrorKeys.category.successfullyUpdated = The category with id=[{0}] was successfully updated;
error.util.ErrorKeys.category.successfullyDeleted = The category with id=[{0}] was successfully deleted;
error.util.ErrorKeys.product.notFound = Product not found with id: [{0}]";
error.util.ErrorKeys.product.notFoundName = Product not found with name: [{0}];
error.util.ErrorKeys.product.successfullyCreated = The product  with id [{0}] was successfully created;
error.util.ErrorKeys.product.successfullyUpdated = The product  with id [{0}] was successfully updated;
error.util.ErrorKeys.product.successfullyDeleted = The product  with id [{0}] was successfully deleted;
