spring.application.name=catalog_service
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=catalog_db
#CORS
cors.mapping.path=/**
cors.allowed.origins=http://localhost:3000
cors.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed.headers=*