
application:
  auth-server-url: ${APPLICATION_AUTH_SERVER_URL}
  realm: ${APPLICATION_REALM}

spring:

  application:
    name: ${SPRING_APPLICATION_NAME}
    auth-server-url: ${APPLICATION_AUTH_SERVER_URL}
    realm: ${REALM}
    client-id: ${CLIEND_ID}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: ${KEYCLOAK_AUTHORIZATION_GRANT_TYPE}
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: ${KEYCLOAK_SCOPE}

        provider:
          keycloak:
            issuer-uri: ${PROVIDER_KEYCLOAK_ISSUER_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    root: INFO
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
server:
  port: 8080
