spring.application.name=catalog_service
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=catalog_db
spring.profiles.active=dev

#APP
app.init.categories=true
app.init.products=true
#app.init.categories.force=false

#CORS
cors.mapping.path=/**
cors.allowed.origins=http://localhost:3000
cors.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed.headers=*

#MinIO
minio.endpoint=http://minio:9000
#minio.public-endpoint =http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
#minio.bucket-name=categories

logging.level.org.mongodb.driver=WARN
