spring.application.name=catalog_service
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=catalog_db
spring.profiles.active=dev

#APP
app.init.categories=true
app.init.products=true
#app.init.categories.force=false

#CORS
cors.mapping.path=/**
cors.allowed.origins=http://localhost:3000
cors.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed.headers=*

#MinIO
minio.endpoint=http://minio:9000
#minio.public-endpoint =http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
#minio.bucket-name=categories

#Logging
logging.level.org.mongodb.driver=WARN

logging.file.name=/app/logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n
logging.logback.rollingpolicy.file-name-pattern=/app/logs/application.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=3
logging.logback.rollingpolicy.total-size-cap=100MB
logging.level.root=INFO

#Banner
spring.main.banner-mode=console
spring.output.ansi.enabled=ALWAYS
